version: '3'
services:
  api:
    container_name: rails-api
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/api
    ports:
      - 3001:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0.34
    container_name: mysql
    volumes:
      - db-volume:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"

  front:
    container_name: react
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  prism:
    container_name: prism
    build: ./openapi/
    ports:
      - "3030:3030"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/openapi.yml
    volumes:
      - ./openapi/openapi.yml:/openapi/openapi.yml
    ports:
      - "3031:8080"
  redoc:
    image: redocly/redoc
    container_name: redoc
    environment:
      - SPEC_URL=/openapi/openapi.yml
    volumes:
      - ./openapi/openapi.yml:/usr/share/nginx/html/openapi/openapi.yml
    ports:
      - "3032:80"

volumes:
  db-volume:
