openapi: 3.0.0
info:
  title: 投稿アプリAPI
  version: 1.0.0

paths:
  /v1/users:
    post:
      description: ユーザー作成
  /v1/users/{userId}:
    get:
      summary: ユーザー詳細
      description: Retrieve user information by providing a unique user ID.
      parameters:
        - name: userId
          in: path
          description: The unique identifier of the user.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: User information retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  email:
                    type: string
                    format: email
                  profile_path:
                    type: string
                  created_at:
                    type: string
                    format: date
                  updated_at:
                    type: string
                    format: date
        "404":
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '404 Not Found'
  /v1/login:
    post:
      description: ログイン
  /v1/logout:
  /v1/posts:
    get:
      description: 投稿一覧取得
      responses:
        "200":
          description: Post information retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  user_id:
                    type: integer
                    format: int64
                  title:
                    type: string
                    example: "タイトル"
                  content:
                    type: string
                    example: "内容"
                  created_at:
                    type: string
                    format: date
                  updated_at:
                    type: string
                    format: date
    post:
      summary: "投稿作成"
      description: 投稿作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: 'タイトル'
                content:
                  type: string
                  example: '内容'
      responses:
        "201":
          description: Success
          content:
            "application/json":
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                    example: '投稿タイトル'
                  content:
                    type: string
                    example: '内容'
        "401":
          $ref: "#/components/responses/Unauthorized"
        "400":
          $ref: "#/components/responses/BadRequest"
  /v1/posts/{postId}:
    get:
      description: 投稿詳細
      responses:
    put:
      description: 投稿の編集
      responses:
components:
  responses:
    Authorized:
      description: "認証成功"
      content:
        application/json:
          schema:
            type: object
            properties:
              access_token:
                type: string
              id_token:
                type: string
              user_id:
                type: number
            required:
              - access_token
              - id_token
              - user_id
    BadRequest:
      description: Bad Request
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
    NotFound:
      description: Not Found